{% set version = "0.8.7" %}

package:
  name: fsspec
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/fsspec/fsspec-{{ version }}.tar.gz
  sha256: 4b11557a90ac637089b10afa4c77adf42080c0696f6f2771c41ce92d73c41432

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python >=3.5
    - pip
    - jinja2
  run:
    - python >=3.5

test:
  requires:
    - pip
    # TODO: remove, probably
    - python <3.8
  imports:
    - fsspec
  commands:
    - pip check

about:
  home: https://github.com/intake/filesystem_spec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A specification for pythonic filesystems
  doc_url: https://filesystem-spec.readthedocs.io
  doc_source_url: https://github.com/intake/filesystem_spec/tree/master/docs
  description: >
    To produce a template or specification for a file-system interface, that
    specific implementations should follow, so that applications making use of
    them can rely on a common behaviour and not have to worry about the specific
    internal implementation decisions with any given backend. Many such
    implementations are included in this package, or in sister projects such as
    s3fs and gcsfs.

    In addition, if this is well-designed, then additional functionality, such
    as a key-value store or FUSE mounting of the file-system implementation may
    be available for all implementations "for free".

extra:
  recipe-maintainers:
    - martindurant
    - TomAugspurger
